name: EIP MIRROR

on:
  push:

env:
  MIRROR_URL: "git@github.com:EpitechPromo2026/B-EIP-600-PAR-6-1-eiptek3-evan.labourdette.git"

jobs:
  push_to_mirror:
    name: Mirorring
    runs-on: ubuntu-latest
    steps:
      - name: Check repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Check mirorring
        uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: ${{ env.MIRROR_URL }}
          ssh_private_key: ${{ secrets.GIT_SSH_PRIVATE_KEY }}
